sap.ui.define([

], function () {
    return {
        LOAD_TODOS: 'LOAD_TODOS',
        LOAD_TODOS_SUCCESS: 'LOAD_TODOS_SUCCESS',
        LOAD_TODOS_FAIL: 'LOAD_TODOS_FAIL',

        ADD_TODO: 'ADD_TODO',
        ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
        ADD_TODO_FAIL: 'ADD_TODO_FAIL',

        DELETE_TODO: 'DELETE_TODO',
        DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
        DELETE_TODO_FAIL: 'DELETE_TODO_FAIL',
        
        TOGGLE_TODO: 'TOGGLE_TODO',
        TOGGLE_TODO_SUCCESS: 'TOGGLE_TODO_SUCCESS',
        TOGGLE_TODO_FAIL: 'TOGGLE_TODO_FAIL',

        CLEAR_COMPLETED_TODOS: 'CLEAR_COMPLETED_TODOS',
        CLEAR_COMPLETED_TODOS_SUCCESS: 'CLEAR_COMPLETED_TODOS_SUCCESS',
        CLEAR_COMPLETED_TODOS_FAIL: 'CLEAR_COMPLETED_TODOS_FAIL'
    };
});